import express from 'express';
const router = express.Router();

const products = [
  { id: '1', name: 'Digital X-Ray System DR-3000', sku: 'MTX-IMG-001', description: 'High-resolution digital radiography system with advanced image processing, wireless detector, and DICOM compatibility. Ideal for hospitals and diagnostic centers.', shortDescription: 'Advanced DR system with wireless detector', category: 'Imaging Equipment', price: 2850000, priceOnRequest: false, images: ['https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600'], brand: 'Philips', origin: 'Netherlands', inStock: true, featured: true, tags: ['xray', 'imaging', 'diagnostic'], specifications: [{ key: 'Detector Size', value: '43x43 cm' }, { key: 'Resolution', value: '3.1 lp/mm' }, { key: 'Power', value: '380V/50Hz' }] },
  { id: '2', name: 'Automated Hematology Analyzer BC-6800', sku: 'MTX-LAB-001', description: 'Full 5-part differential hematology analyzer with 60 samples/hour throughput. Features advanced algorithms for reliable CBC with differential results.', shortDescription: '5-part differential, 60 samples/hour', category: 'Laboratory Equipment', price: 485000, priceOnRequest: false, images: ['https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600'], brand: 'Mindray', origin: 'China', inStock: true, featured: true, tags: ['hematology', 'CBC', 'blood count'], specifications: [{ key: 'Throughput', value: '60 samples/hr' }, { key: 'Parameters', value: '29 parameters' }, { key: 'Sample Volume', value: '9.9µL' }] },
  { id: '3', name: 'ICU Patient Monitor PM-9000', sku: 'MTX-MON-001', description: 'Comprehensive bedside monitor for ICU and critical care. Monitors ECG, SpO2, NIBP, temperature, and CO2 with 15" touchscreen display and central station connectivity.', shortDescription: 'Multi-parameter ICU monitor, 15" touch', category: 'Patient Monitoring', price: 320000, priceOnRequest: false, images: ['https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=600'], brand: 'GE Healthcare', origin: 'USA', inStock: true, featured: true, tags: ['ICU', 'monitoring', 'critical care'], specifications: [{ key: 'Display', value: '15" color touchscreen' }, { key: 'Parameters', value: 'ECG, SpO2, NIBP, Temp, CO2' }, { key: 'Battery', value: '4 hours backup' }] },
  { id: '4', name: 'Laparoscopic Surgery Tower', sku: 'MTX-SRG-001', description: 'Complete HD laparoscopic surgery system including 10mm 0° and 30° telescopes, full HD camera, LED light source, insufflator, and 27" HD monitor. Ready-to-use surgical package.', shortDescription: 'Complete HD laparoscopy package', category: 'Surgical Instruments', price: null, priceOnRequest: true, images: ['https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=600'], brand: 'Karl Storz', origin: 'Germany', inStock: true, featured: true, tags: ['laparoscopy', 'surgery', 'HD'], specifications: [{ key: 'Camera', value: 'Full HD 1080p' }, { key: 'Light Source', value: 'LED 300W' }, { key: 'Monitor', value: '27" HD Medical Grade' }] },
  { id: '5', name: 'Ultrasound System DC-70', sku: 'MTX-IMG-002', description: 'Premium color Doppler ultrasound with 21.5" LED monitor. Supports abdominal, cardiac, obstetric, and vascular applications with excellent image clarity.', shortDescription: 'Premium color Doppler, multi-application', category: 'Imaging Equipment', price: 1250000, priceOnRequest: false, images: ['https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=600'], brand: 'Mindray', origin: 'China', inStock: true, featured: false, tags: ['ultrasound', 'doppler', 'imaging'], specifications: [{ key: 'Monitor', value: '21.5" LED' }, { key: 'Probes', value: 'Convex, Linear, Phased' }, { key: 'Storage', value: '500GB HDD' }] },
  { id: '6', name: 'Biochemistry Analyzer BS-200E', sku: 'MTX-LAB-002', description: 'Fully automated random access biochemistry analyzer. 200 tests per hour with 45-position onboard reagent capacity. Ideal for medium to large volume labs.', shortDescription: 'Fully automated, 200 tests/hour', category: 'Laboratory Equipment', price: 680000, priceOnRequest: false, images: ['https://images.unsplash.com/photo-1579154204601-01588f351e67?w=600'], brand: 'Mindray', origin: 'China', inStock: true, featured: false, tags: ['biochemistry', 'clinical chemistry', 'analyzer'], specifications: [{ key: 'Throughput', value: '200 tests/hr' }, { key: 'Sample Types', value: 'Serum, plasma, urine' }, { key: 'Reagent Positions', value: '45 onboard' }] },
  { id: '7', name: 'Defibrillator BeneHeart D6', sku: 'MTX-MON-002', description: 'Biphasic defibrillator with AED, pacing, and monitoring functions. Large 7.5" display, rechargeable battery, and comprehensive cardiac monitoring capabilities.', shortDescription: 'Biphasic defib with AED & pacing', category: 'Patient Monitoring', price: 185000, priceOnRequest: false, images: ['https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=600'], brand: 'Mindray', origin: 'China', inStock: true, featured: false, tags: ['defibrillator', 'AED', 'cardiac'], specifications: [{ key: 'Energy', value: '1-360 Joules' }, { key: 'Display', value: '7.5" color LCD' }, { key: 'Battery', value: '3 hours operation' }] },
  { id: '8', name: 'Dental Unit CEFLA C-PLEX', sku: 'MTX-DEN-001', description: 'Modern dental treatment unit with LED operating light, integrated scaler, air rotor, micromotor, and three-way syringe. Ergonomic design for both dentist and patient comfort.', shortDescription: 'Full dental unit with LED light', category: 'Dental Equipment', price: 420000, priceOnRequest: false, images: ['https://images.unsplash.com/photo-1609207807107-e8e3fb78f4d3?w=600'], brand: 'CEFLA', origin: 'Italy', inStock: false, featured: false, tags: ['dental', 'dentistry', 'treatment unit'], specifications: [{ key: 'Light', value: 'LED 30,000 lux' }, { key: 'Chair', value: 'Electric 4-movement' }, { key: 'Water Bottle', value: '750ml' }] },
  { id: '9', name: 'Surgical Suction Unit', sku: 'MTX-SRG-002', description: 'High-performance surgical suction machine for operating theatres and ICUs. Dual jar system, adjustable vacuum, portable design with silent motor operation.', shortDescription: 'Dual jar, high-performance suction', category: 'Surgical Instruments', price: 45000, priceOnRequest: false, images: ['https://images.unsplash.com/photo-1584362917165-526a968579e8?w=600'], brand: 'Medela', origin: 'Switzerland', inStock: true, featured: false, tags: ['suction', 'surgical', 'theatre'], specifications: [{ key: 'Vacuum', value: '-0.08 MPa max' }, { key: 'Jar Capacity', value: '2x 1000ml' }, { key: 'Noise Level', value: '<60dB' }] },
  { id: '10', name: 'PCR Thermocycler GeneAmp 9700', sku: 'MTX-LAB-003', description: 'Fast and reliable PCR thermocycler with 96-well block, gradient function, and PC connectivity. Essential for molecular diagnostics, research, and infectious disease testing.', shortDescription: '96-well PCR with gradient & PC link', category: 'Laboratory Equipment', price: null, priceOnRequest: true, images: ['https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600'], brand: 'Applied Biosystems', origin: 'USA', inStock: true, featured: false, tags: ['PCR', 'molecular', 'diagnostics'], specifications: [{ key: 'Well Plate', value: '96-well standard' }, { key: 'Ramp Rate', value: '3.3°C/sec' }, { key: 'Temp Range', value: '0-100°C' }] },
  { id: '11', name: 'Hospital Bed with Mattress', sku: 'MTX-GEN-001', description: 'Electric 3-function hospital bed with ABS side rails, central locking castors, IV pole socket, and premium anti-decubitus mattress. Ideal for wards and private rooms.', shortDescription: 'Electric 3-function bed + mattress', category: 'Rehabilitation Equipment', price: 95000, priceOnRequest: false, images: ['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600'], brand: 'Linet', origin: 'Czech Republic', inStock: true, featured: false, tags: ['hospital bed', 'ward', 'electric'], specifications: [{ key: 'Functions', value: '3 electric motors' }, { key: 'Load Capacity', value: '250kg' }, { key: 'Dimensions', value: '2100x900mm' }] },
  { id: '12', name: 'Autoclave Steam Sterilizer 23L', sku: 'MTX-CON-001', description: 'Benchtop pre-vacuum autoclave for sterilizing wrapped and unwrapped instruments. 23-liter chamber, multiple sterilization cycles, and digital display for complete control.', shortDescription: 'Pre-vacuum benchtop autoclave, 23L', category: 'Consumables & Supplies', price: 75000, priceOnRequest: false, images: ['https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=600'], brand: 'Tuttnauer', origin: 'Israel', inStock: true, featured: false, tags: ['autoclave', 'sterilizer', 'infection control'], specifications: [{ key: 'Chamber Volume', value: '23 Liters' }, { key: 'Temperature', value: '121/134°C' }, { key: 'Cycles', value: '3 standard + custom' }] }
];

// GET all products
router.get('/', (req, res) => {
  let result = [...products];
  const { category, search, featured, inStock, page = 1, limit = 12 } = req.query;
  
  if (category && category !== 'all') result = result.filter(p => p.category === category);
  if (search) result = result.filter(p => p.name.toLowerCase().includes(search.toLowerCase()) || p.description.toLowerCase().includes(search.toLowerCase()) || p.tags?.some(t => t.toLowerCase().includes(search.toLowerCase())));
  if (featured === 'true') result = result.filter(p => p.featured);
  if (inStock === 'true') result = result.filter(p => p.inStock);

  const total = result.length;
  const start = (page - 1) * limit;
  const paginated = result.slice(start, start + Number(limit));

  res.json({ products: paginated, total, pages: Math.ceil(total / limit), page: Number(page) });
});

// GET categories
router.get('/categories', (req, res) => {
  const cats = [...new Set(products.map(p => p.category))];
  const counts = cats.map(c => ({ name: c, count: products.filter(p => p.category === c).length }));
  res.json(counts);
});

// GET single product
router.get('/:id', (req, res) => {
  const product = products.find(p => p.id === req.params.id);
  if (!product) return res.status(404).json({ message: 'Product not found' });
  res.json(product);
});

export default router;
